# Generated by Django 6.0 on 2025-12-04 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AmmoSales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('PISTOL', 'Пистолетные патроны'), ('RIFLE', 'Винтовочные патроны'), ('SHOTGUN', 'Дробовые патроны'), ('SPORT', 'Спортивные патроны'), ('HUNTING', 'Охотничьи патроны')], default='PISTOL', max_length=200, verbose_name='Тип патронов')),
                ('caliber', models.CharField(choices=[('9x19', '9x19 мм (пистолетный)'), ('7.62x39', '7.62x39 мм (автоматный)'), ('5.45x39', '5.45x39 мм (автоматный)'), ('223REM', '.223 Remington (винтовочный)'), ('308WIN', '.308 Winchester (винтовочный)'), ('12GA', '12 калибр (дробовой)'), ('762x54', '7.62x54 мм (винтовочный)'), ('9x18', '9x18 мм (пистолетный)'), ('45ACP', '.45 ACP (пистолетный)')], default='9x19', max_length=20, verbose_name='Калибр')),
                ('manufacturer', models.CharField(default='Тульский патронный завод', max_length=100, verbose_name='Производитель')),
                ('price', models.IntegerField(default=1500, verbose_name='Цена (руб)')),
                ('quantity', models.IntegerField(default=20, verbose_name='Количество в упаковке')),
                ('description', models.TextField(blank=True, default='Качественные патроны для стрельбы', verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
            ],
            options={
                'verbose_name': 'Патрон',
                'verbose_name_plural': 'Патроны',
                'ordering': ['caliber', 'price'],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=100, verbose_name='Название услуги')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('duration_minute', models.IntegerField(verbose_name='Продолжительность (минуты)')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('hire_date', models.DateField(verbose_name='Дата найма')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название цели')),
                ('target_type', models.CharField(max_length=50, verbose_name='Тип цели')),
                ('difficulty_level', models.IntegerField(verbose_name='Уровень сложности')),
            ],
            options={
                'verbose_name': 'Цель',
                'verbose_name_plural': 'Цели',
            },
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weapon_name', models.CharField(max_length=100, verbose_name='Название оружия')),
                ('weapon_type', models.CharField(max_length=50, verbose_name='Тип оружия')),
                ('caliber', models.CharField(max_length=20, verbose_name='Калибр')),
                ('status', models.CharField(choices=[('STATUS_AVAILABLE', 'Доступно'), ('STATUS_IN_USE', 'В использовании'), ('STATUS_MAINTENANCE', 'На обслуживании'), ('STATUS_BROKEN', 'Сломан'), ('STATUS_RESERVED', 'Зарезервировано')], max_length=50, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Оружие',
                'verbose_name_plural': 'Оружие',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateField(verbose_name='Дата бронирования')),
                ('start_time', models.TimeField(verbose_name='Время начала')),
                ('end_time', models.TimeField(verbose_name='Время окончания')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Общая стоимость')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.client', verbose_name='Клиент')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.service', verbose_name='Услуга')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.staff', verbose_name='Сотрудник')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.target', verbose_name='Цель')),
                ('weapon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.weapon', verbose_name='Оружие')),
            ],
            options={
                'verbose_name': 'Бронирование',
                'verbose_name_plural': 'Бронирования',
            },
        ),
    ]
