# Generated by Django 5.2.8 on 2025-11-25 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ammosales',
            name='total_amount',
        ),
        migrations.AlterField(
            model_name='weapon',
            name='status',
            field=models.CharField(choices=[('STATUS_AVAILABLE', 'Доступно'), ('STATUS_IN_USE', 'В использовании'), ('STATUS_MAINTENANCE', 'На обслуживании'), ('STATUS_BROKEN', 'Сломан'), ('STATUS_RESERVED', 'Зарезервировано')], max_length=50, verbose_name='Статус'),
        ),
    ]
